// Import Next.js Metadata type for page metadata
import type { Metadata } from "next";
// Import Google fonts Geist and Geist_Mono
import { Geist, Geist_Mono } from "next/font/google";
// Import global CSS styles
import "./globals.css";

// Configure Geist Sans font with CSS variable and latin subset
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Configure Geist Mono font with CSS variable and latin subset
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the application (used by Next.js)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component for the application
// Wraps all pages with HTML and body tags, applies fonts and global styles
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Render all child components/pages */}
        {children}
      </body>
    </html>
  );
}
